# Generated by Django 3.2.9 on 2021-12-03 20:38

from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Url',
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='directorsactors',
            name='Image',
            field=models.ImageField(upload_to='directors/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='frameofmovies',
            name='Image',
            field=models.ImageField(max_length=50, upload_to=movies.models.get_url_for_frames, verbose_name='Кадры'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='Url',
            field=models.SlugField(max_length=25, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Draft',
            field=models.BooleanField(default=False, verbose_name='Черновичоr ли ты?'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.ImageField(upload_to=movies.models.user_directory_path, verbose_name='Постеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Url',
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Movie',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Parent',
            field=models.ForeignKey(blank=True, default='Name', null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.reviews', to_field='Name', verbose_name='Родитель'),
        ),
    ]
