# Generated by Django 3.2.9 on 2021-12-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211204_0238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstars',
            options={'ordering': ['-Value'], 'verbose_name': 'Количество звезд в рейтинге', 'verbose_name_plural': 'Количество звезд в рейтинге'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='Actors',
            field=models.ManyToManyField(to='movies.DirectorsActors', verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat', to='movies.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Draft',
            field=models.BooleanField(default=False, verbose_name='Черновичок ли ты?'),
        ),
        migrations.AlterField(
            model_name='ratingstars',
            name='Value',
            field=models.PositiveSmallIntegerField(verbose_name='Значение рейтинга'),
        ),
    ]
