# Generated by Django 3.2.9 on 2021-12-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211207_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='Description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='Name_en',
            field=models.CharField(max_length=500, null=True, unique=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='Name_ru',
            field=models.CharField(max_length=500, null=True, unique=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='directorsactors',
            name='Age_en',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='directorsactors',
            name='Age_ru',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='directorsactors',
            name='Description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='directorsactors',
            name='Description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='directorsactors',
            name='Name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='directorsactors',
            name='Name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='frameofmovies',
            name='Description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='frameofmovies',
            name='Description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='frameofmovies',
            name='Title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='frameofmovies',
            name='Title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='genre',
            name='Description_en',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='genre',
            name='Description_ru',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='genre',
            name='Name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='genre',
            name='Name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Description_en',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Description_ru',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Tagline_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Tagline_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Title_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Title_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
    ]
